package com.ooftf.docking.annotation;

/**
 * @author ooftf
 * @email 994749769@qq.com
 * @date 2018/12/11 0011
 */
public class Consts {
    public static final String PROJECT = "Docking";
    public static final String SEPARATOR = "$$";
    public static final String SUFFIX_APPLICATION = "Application";
    public static final String DOT = ".";

    public static final String TAG = "Docking";
    /**
     * 生成文件的报名
     */
    public static final String REGISTER_PACKAGE_NAME = "com.ooftf.docking.register";
    /**
     * MODULE_NAME 需要使用时在gradle中指定
     */
    public static final String KEY_MODULE_NAME = "DOCKING_MODULE_NAME";

    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY Docking.";

    /**
     * 被注解的类需要实现的接口
     */
    public static final String IAPPLICATION_INTERFACE_NAME = "com.ooftf.docking.api.IApplication";
    /**
     * 生成类需要实现的接口
     */
    public static final String GEN_CLASS_INTERFACE_NAME = "com.ooftf.docking.api.IApplicationRegister";
    /**
     * 注解的全称
     */
    public static final String APPLICATION_ANNOTATION_NAME = "com.ooftf.docking.annotation.Application";

}
