package com.ooftf.docking.compiler;

/**
 * @author ooftf
 * @email 994749769@qq.com
 * @date 2018/12/3 0003
 */
public class Consts {
    public static final String SEPARATOR = "$$";

    public static final String PROJECT = "Docking";

    public static final String KEY_MODULE_NAME = "DOCKING_MODULE_NAME";

    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER.";


    public static final String IAPPLICATION = "com.ooftf.docking.api.IApplication";

    public static final String REGISTER_PACKAGE_NAME = "com.ooftf.docking.register";


}
